FROM node:21

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json .

# Install all dependencies, including devDependencies
RUN npm install

# Copy the rest of the frontend files
COPY . .

# Expose port 3000
EXPOSE 3000

# Start the app in development mode
CMD ["npm", "run", "start"]
