from sqlalchemy import Column, Integer, String, Float, Date, JSON, ForeignKey
from sqlalchemy.orm import relationship
from ..db.database import Base

class AIProject(Base):
    __tablename__ = "ai_projects"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, index=True)
    description = Column(String)
    creation_date = Column(Date)
    last_updated_date = Column(Date)
    status = Column(String)
    start_date = Column(Date)
    estimated_completion_date = Column(Date)
    actual_completion_date = Column(Date)
    sponsor = Column(String)
    project_manager = Column(String)
    team_members = Column(JSON)
    ai_models = Column(JSON)
    programming_languages = Column(JSON)
    frameworks_and_libraries = Column(JSON)
    repository_uri = Column(String)
    development_environment = Column(String)
    data_sources = Column(JSON)
    data_storage_location = Column(String)
    data_sensitivity_level = Column(String)
    data_retention_policy = Column(String)
    risk_assessment_score = Column(Float)
    compliance_status = Column(String)
    applicable_policies = Column(JSON)
    regulatory_requirements = Column(JSON)
    kpis = Column(JSON)
    model_accuracy = Column(Float)
    processing_time = Column(Float)
    resource_usage = Column(JSON)
    potential_biases = Column(JSON)
    fairness_measures = Column(JSON)
    transparency_level = Column(String)
    deployment_environment = Column(String)
    api_endpoints = Column(JSON)
    scalability_info = Column(String)
    technical_documentation_uri = Column(String)
    user_guide_uri = Column(String)
    model_cards = Column(JSON)
    version_history = Column(JSON)
    changelog = Column(JSON)
    allocated_budget = Column(Float)
    current_spend = Column(Float)
    resource_allocation = Column(JSON)
    external_dependencies = Column(JSON)
    internal_project_dependencies = Column(JSON)
    security_clearance_level = Column(String)
    access_control_list = Column(JSON)
    encryption_details = Column(String)
    monitoring_tools = Column(JSON)
    maintenance_schedule = Column(String)
    incident_response_plan = Column(String)